// libs/cms/ui/src/lib/editor/section-library-modal.component.ts
import { ChangeDetectionStrategy, Component, EventEmitter, Input, Output } from '@angular/core';
import { SectionDefinition } from '@flex-erp/types';
import { CmsButtonComponent } from '../primitives/button/cms-button.component';
import { CmsInputComponent } from '../primitives/input/cms-input.component';
import { CmsScrollAreaComponent } from '../primitives/scroll-area/cms-scroll-area.component';
import { CmsDialogComponent } from '../primitives/dialog/cms-dialog.component';
import { CmsTabsComponent, CmsTabItem } from '../primitives/tabs/cms-tabs.component';

const CATEGORIES: CmsTabItem[] = [
  { value: 'all', label: 'All' },
  { value: 'header', label: 'Header' },
  { value: 'hero', label: 'Hero' },
  { value: 'collections', label: 'Collections' },
  { value: 'product', label: 'Product' },
  { value: 'marketing', label: 'Marketing' },
  { value: 'footer', label: 'Footer' },
];

@Component({
  selector: 'cms-section-library-modal',
  standalone: true,
  imports: [CmsButtonComponent, CmsInputComponent, CmsScrollAreaComponent, CmsDialogComponent, CmsTabsComponent],
  templateUrl: './section-library-modal.component.html',
  changeDetection: ChangeDetectionStrategy.OnPush,
})
export class CmsSectionLibraryModalComponent {
  @Input() open = false;
  @Input() sectionDefinitions: SectionDefinition[] = [];

  @Output() requestClose = new EventEmitter<void>();
  @Output() addSection = new EventEmitter<SectionDefinition>();

  search = '';
  activeCategory = 'all';

  get categories() {
    return CATEGORIES;
  }

  filteredSections(): SectionDefinition[] {
    const search = this.search.toLowerCase();
    return this.sectionDefinitions.filter((def) => {
      const matchesSearch =
        def.name.toLowerCase().includes(search) || def.description.toLowerCase().includes(search);
      const matchesCategory = this.activeCategory === 'all' || def.category === this.activeCategory;
      return matchesSearch && matchesCategory;
    });
  }

  iconClass(icon: string): string {
    const map: Record<string, string> = {
      'layout-template': 'pi pi-table',
      image: 'pi pi-image',
      columns: 'pi pi-sliders-h',
      'grid-3x3': 'pi pi-th-large',
      mail: 'pi pi-envelope',
      'panel-bottom': 'pi pi-window-maximize',
      megaphone: 'pi pi-megaphone',
      'credit-card': 'pi pi-credit-card',
      quote: 'pi pi-quote-left',
      'folder-kanban': 'pi pi-sitemap',
    };
    return map[icon] || 'pi pi-table';
  }

  handleAdd(definition: SectionDefinition): void {
    this.addSection.emit(definition);
    this.requestClose.emit();
  }
}

<cms-dialog
  [open]="open"
  (openChange)="requestClose.emit()"
  contentClass="w-full max-w-3xl max-h-[80vh] p-0 gap-0 overflow-hidden rounded-lg border border-ui-border-base bg-ui-bg-base shadow-lg"
>
  <div class="px-6 py-4 border-b border-ui-border-base">
    <h2 class="text-lg font-semibold text-ui-fg-base">Add Section</h2>
  </div>

  <div class="px-6 py-4 border-b border-ui-border-base space-y-4">
    <div class="relative">
      <i class="pi pi-search absolute left-3 top-1/2 -translate-y-1/2 text-ui-fg-muted text-xs"></i>
      <cms-input
        placeholder="Search sections..."
        [value]="search"
        (valueChange)="search = $event"
        className="pl-9"
      ></cms-input>
    </div>

    <cms-tabs [tabs]="categories" [value]="activeCategory" (valueChange)="activeCategory = $event"></cms-tabs>
  </div>

  <cms-scroll-area className="flex-1 max-h-[400px]">
    <div class="p-6 grid grid-cols-2 md:grid-cols-3 gap-4">
      @if (filteredSections().length === 0) {
        <div class="col-span-full text-center py-12 text-ui-fg-muted">
          <p class="font-medium">No sections found</p>
          <p class="text-sm mt-1">Try adjusting your search or category</p>
        </div>
      } @else {
        @for (def of filteredSections(); track def.type) {
          <button
            type="button"
            (click)="handleAdd(def)"
            class="group p-4 rounded-xl border border-ui-border-base bg-ui-bg-base hover:border-ui-border-interactive hover:shadow-md transition-all text-left"
          >
            <div class="w-10 h-10 rounded-lg bg-ui-bg-subtle flex items-center justify-center mb-3 group-hover:bg-ui-bg-subtle-hover transition-colors">
              <i [class]="iconClass(def.icon) + ' text-ui-fg-base'"></i>
            </div>
            <h3 class="font-medium text-sm mb-1">{{ def.name }}</h3>
            <p class="text-xs text-ui-fg-muted line-clamp-2">{{ def.description }}</p>
          </button>
        }
      }
    </div>
  </cms-scroll-area>
</cms-dialog>

// visual-website-builder-main/src/components/editor/SectionLibraryModal.tsx
import { useState } from 'react';
import { 
  X, 
  Search,
  LayoutTemplate,
  Image,
  Columns,
  Grid3X3,
  Mail,
  PanelBottom,
  Megaphone,
  CreditCard,
  Quote,
  FolderKanban
} from 'lucide-react';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { ScrollArea } from '@/components/ui/scroll-area';
import {
  Dialog,
  DialogContent,
  DialogHeader,
  DialogTitle,
} from '@/components/ui/dialog';
import { cn } from '@/lib/utils';
import { sectionDefinitions } from '@/data/mockData';
import { Section, SectionDefinition } from '@/types/editor';

const iconMap: Record<string, React.ElementType> = {
  'layout-template': LayoutTemplate,
  'image': Image,
  'columns': Columns,
  'grid-3x3': Grid3X3,
  'mail': Mail,
  'panel-bottom': PanelBottom,
  'megaphone': Megaphone,
  'credit-card': CreditCard,
  'quote': Quote,
  'folder-kanban': FolderKanban,
};

const categories = [
  { id: 'all', label: 'All' },
  { id: 'header', label: 'Header' },
  { id: 'hero', label: 'Hero' },
  { id: 'collections', label: 'Collections' },
  { id: 'product', label: 'Product' },
  { id: 'marketing', label: 'Marketing' },
  { id: 'footer', label: 'Footer' },
];

interface SectionLibraryModalProps {
  open: boolean;
  onClose: () => void;
  onAdd: (section: Section) => void;
}

export function SectionLibraryModal({ open, onClose, onAdd }: SectionLibraryModalProps) {
  const [search, setSearch] = useState('');
  const [activeCategory, setActiveCategory] = useState('all');

  const filteredSections = sectionDefinitions.filter((def) => {
    const matchesSearch = def.name.toLowerCase().includes(search.toLowerCase()) ||
      def.description.toLowerCase().includes(search.toLowerCase());
    const matchesCategory = activeCategory === 'all' || def.category === activeCategory;
    return matchesSearch && matchesCategory;
  });

  const handleAdd = (def: SectionDefinition) => {
    const newSection: Section = {
      id: `${def.type}-${Date.now()}`,
      type: def.type,
      name: def.name,
      icon: def.icon,
      visible: true,
      settings: { ...def.defaultSettings },
      blocks: [],
    };
    onAdd(newSection);
    onClose();
  };

  return (
    <Dialog open={open} onOpenChange={(isOpen) => !isOpen && onClose()}>
      <DialogContent className="max-w-3xl max-h-[80vh] p-0 gap-0 overflow-hidden">
        <DialogHeader className="px-6 py-4 border-b border-border">
          <DialogTitle className="text-lg font-semibold">Add Section</DialogTitle>
        </DialogHeader>

        <div className="px-6 py-4 border-b border-border space-y-4">
          {/* Search */}
          <div className="relative">
            <Search className="absolute left-3 top-1/2 -translate-y-1/2 w-4 h-4 text-muted-foreground" />
            <Input
              placeholder="Search sections..."
              value={search}
              onChange={(e) => setSearch(e.target.value)}
              className="pl-10"
            />
          </div>

          {/* Category Tabs */}
          <div className="flex gap-2 flex-wrap">
            {categories.map((cat) => (
              <button
                key={cat.id}
                onClick={() => setActiveCategory(cat.id)}
                className={cn(
                  'px-3 py-1.5 rounded-full text-sm font-medium transition-colors',
                  activeCategory === cat.id
                    ? 'bg-primary text-primary-foreground'
                    : 'bg-secondary text-secondary-foreground hover:bg-accent'
                )}
              >
                {cat.label}
              </button>
            ))}
          </div>
        </div>

        {/* Sections Grid */}
        <ScrollArea className="flex-1 max-h-[400px]">
          <div className="p-6 grid grid-cols-2 md:grid-cols-3 gap-4">
            {filteredSections.length === 0 ? (
              <div className="col-span-full text-center py-12 text-muted-foreground">
                <p className="font-medium">No sections found</p>
                <p className="text-sm mt-1">Try adjusting your search or category</p>
              </div>
            ) : (
              filteredSections.map((def) => {
                const Icon = iconMap[def.icon] || LayoutTemplate;
                return (
                  <button
                    key={def.type}
                    onClick={() => handleAdd(def)}
                    className="group p-4 rounded-xl border border-border bg-card hover:border-primary hover:shadow-md transition-all text-left"
                  >
                    <div className="w-10 h-10 rounded-lg bg-primary/10 flex items-center justify-center mb-3 group-hover:bg-primary/20 transition-colors">
                      <Icon className="w-5 h-5 text-primary" />
                    </div>
                    <h3 className="font-medium text-sm mb-1">{def.name}</h3>
                    <p className="text-xs text-muted-foreground line-clamp-2">{def.description}</p>
                  </button>
                );
              })
            )}
          </div>
        </ScrollArea>
      </DialogContent>
    </Dialog>
  );
}
