// libs/cms/ui/src/lib/editor/top-bar.component.ts
import { ChangeDetectionStrategy, Component, EventEmitter, Input, Output } from '@angular/core';
import { DeviceType, PageType } from '@flex-erp/types';
import { CmsButtonComponent } from '../primitives/button/cms-button.component';
import { CmsInputComponent } from '../primitives/input/cms-input.component';
import {
  RdxDropdownMenuContentDirective,
  RdxDropdownMenuItemDirective,
  RdxDropdownMenuTriggerDirective,
} from '@radix-ng/primitives/dropdown-menu';
import { RdxTooltipModule } from '@radix-ng/primitives/tooltip';
import {
  LucideAngularModule,
  Monitor,
  Tablet,
  Smartphone,
  Undo2,
  Redo2,
  Save,
  Rocket,
  ChevronDown,
  Check,
  Palette
} from 'lucide-angular';

const PAGES: { value: PageType; label: string }[] = [
  { value: 'home', label: 'Home' },
  { value: 'collection', label: 'Collection' },
  { value: 'product', label: 'Product' },
];

const DEVICES: { value: DeviceType; label: string; icon: string }[] = [
  { value: 'desktop', label: 'Desktop', icon: 'pi pi-desktop' },
  { value: 'tablet', label: 'Tablet', icon: 'pi pi-tablet' },
  { value: 'mobile', label: 'Mobile', icon: 'pi pi-mobile' },
];



@Component({
  selector: 'cms-top-bar',
  standalone: true,
  imports: [
    CmsButtonComponent,
    CmsInputComponent,
    RdxDropdownMenuTriggerDirective,
    RdxDropdownMenuContentDirective,
    RdxDropdownMenuItemDirective,
    RdxTooltipModule,
    LucideAngularModule,
  ],
  templateUrl: './top-bar.component.html',
  changeDetection: ChangeDetectionStrategy.OnPush,
})
export class CmsTopBarComponent {
  @Input() storeName = '';
  @Input() currentPage: PageType = 'home';
  @Input() viewportMode: DeviceType = 'desktop';
  @Input() canUndo = false;
  @Input() canRedo = false;

  @Output() storeNameChange = new EventEmitter<string>();
  @Output() currentPageChange = new EventEmitter<PageType>();
  @Output() viewportModeChange = new EventEmitter<DeviceType>();
  @Output() undo = new EventEmitter<void>();
  @Output() redo = new EventEmitter<void>();
  @Output() save = new EventEmitter<void>();
  @Output() publish = new EventEmitter<void>();

  public Undo2 = Undo2;
  public Redo2 = Redo2;
  public Save = Save;
  public Rocket = Rocket;
  public ChevronDown = ChevronDown;
  public Check = Check;
  public Palette = Palette;

  isEditingName = false;
  nameValue = '';

  get pages() {
    return PAGES;
  }

  get devices() {
    return DEVICES;
  }

  get currentPageLabel(): string {
    return PAGES.find((page) => page.value === this.currentPage)?.label ?? '';
  }

  startEditing(): void {
    this.isEditingName = true;
    this.nameValue = this.storeName;
  }

  submitName(): void {
    this.storeNameChange.emit(this.nameValue.trim() || this.storeName);
    this.isEditingName = false;
  }
}

<header
  class="h-14 w-full justify-between bg-ui-bg-base border-b border-ui-border-base flex items-center px-4 gap-4 shrink-0"
>
  <div class="flex items-center gap-3 min-w-[400px]">
    <div
      class="w-8 h-8 rounded-lg bg-ui-bg-interactive flex items-center justify-center"
    >
      <i class="pi pi-palette text-ui-fg-on-color text-sm"></i>
    </div>

    @if (isEditingName) {
    <cms-input
      [value]="nameValue"
      (valueChange)="nameValue = $event"
      (blurred)="submitName()"
      (enterPressed)="submitName()"
      className="h-8 w-40 text-sm font-medium"
    ></cms-input>
    } @else {
    <button
      type="button"
      (click)="startEditing()"
      class="text-sm font-medium text-ui-fg-base hover:text-ui-fg-interactive transition-colors"
    >
      {{ storeName }}
    </button>
    }
  </div>

  <div class="flex-1 flex justify-center">
    <button
      type="button"
      [rdxDropdownMenuTrigger]="pageMenu"
      class="inline-flex items-center justify-center rounded-md text-sm font-medium transition-colors border border-ui-border-base bg-ui-bg-base hover:bg-ui-bg-subtle-hover h-8 px-3 gap-2"
    >
      {{ currentPageLabel | transloco }}
      <i class="pi pi-chevron-down text-xs text-ui-fg-muted"></i>
    </button>

    <ng-template #pageMenu>
      <div
        rdxDropdownMenuContent
        class="rounded-md border border-ui-border-base bg-ui-bg-base p-1 shadow"
      >
        @for (page of pages; track page.value) {
        <button
          type="button"
          rdxDropdownMenuItem
          (click)="currentPageChange.emit(page.value)"
          class="flex w-full items-center gap-2 rounded px-2 py-1.5 text-sm hover:bg-ui-bg-subtle-hover"
        >
          {{ page.label | transloco }}
          @if (currentPage === page.value) {
          <i class="pi pi-check ms-auto text-xs text-ui-fg-interactive"></i>
          }
        </button>
        }
      </div>
    </ng-template>
  </div>

  <div class="flex items-center gap-2 min-w-[400px] justify-end">
    <div class="flex items-center bg-ui-bg-subtle rounded-lg p-1 gap-0.5">
      @for (device of devices; track device.value) {
      <ng-container rdxTooltipRoot>
        <button
          rdxTooltipTrigger
          type="button"
          (click)="viewportModeChange.emit(device.value)"
          class="p-1.5 rounded-md transition-colors cursor-pointer"
          [class.bg-ui-bg-base]="viewportMode === device.value"
          [class.text-ui-fg-base]="viewportMode === device.value"
          [class.text-ui-fg-muted]="viewportMode !== device.value"
          [class.shadow-sm]="viewportMode === device.value"
          [class.hover:bg-ui-bg-subtle-hover]="viewportMode !== device.value"
          [class.border-none]="viewportMode !== device.value"
        >
          <i [class]="device.icon + ' text-sm'"></i>
        </button>
        <ng-template rdxTooltipContent>
          <div
            rdxTooltipContentAttributes
            class="rounded-md bg-ui-bg-base border border-ui-border-base px-2 py-1 text-xs shadow"
          >
            {{ device.label | transloco }}
          </div>
        </ng-template>
      </ng-container>
      }
    </div>

    <div class="w-px h-6 bg-ui-border-base mx-1"></div>

    <ng-container rdxTooltipRoot>
      <button
        rdxTooltipTrigger
        type="button"
        [disabled]="!canUndo"
        (click)="undo.emit()"
        class="inline-flex h-8 w-8 items-center justify-center text-sm font-medium border-none transition-colors hover:bg-ui-bg-subtle-hover cursor-pointer"
      >
        <i-lucide
          [img]="Undo2"
          class="w-4 h-4 text-muted-foreground shrink-0 hover:text-ui-fg-base'"
        ></i-lucide>
      </button>
      <ng-template rdxTooltipContent>
        <div
          rdxTooltipContentAttributes
          class="bg-ui-bg-base  px-2 py-1 text-xs shadow"
        >
          {{ 'cms.editor.actions.undo' | transloco }}
        </div>
      </ng-template>
    </ng-container>

    <ng-container rdxTooltipRoot>
      <button
        rdxTooltipTrigger
        type="button"
        [disabled]="!canRedo"
        (click)="redo.emit()"
        class="inline-flex h-8 w-8 items-center justify-center text-sm font-medium border-none transition-colors hover:bg-ui-bg-subtle-hover cursor-pointer"
      >
        <i-lucide
          [img]="Redo2"
          class="w-4 h-4 text-muted-foreground shrink-0 hover:text-ui-fg-base'"
        ></i-lucide>
      </button>
      <ng-template rdxTooltipContent>
        <div
          rdxTooltipContentAttributes
          class="bg-ui-bg-base  px-2 py-1 text-xs shadow"
        >
          {{ 'cms.editor.actions.redo' | transloco }}
        </div>
      </ng-template>
    </ng-container>

    <div class="w-px h-6 bg-ui-border-base mx-1"></div>

    <cms-button
      variant="outline"
      size="sm"
      (click)="save.emit()"
      className="gap-1.5"
    >
      <i class="pi pi-save text-sm"></i>
      {{ 'cms.editor.actions.save' | transloco }}
    </cms-button>

    <cms-button size="sm" (click)="publish.emit()" className="gap-1.5">
      <i class="pi pi-send text-sm"></i>
      {{ 'cms.editor.actions.publish' | transloco }}
    </cms-button>
  </div>
</header>

// visual-website-builder-main/src/components/editor/TopBar.tsx
import { useState } from 'react';
import { 
  Monitor, 
  Tablet, 
  Smartphone, 
  Undo2, 
  Redo2, 
  Save, 
  Rocket,
  ChevronDown,
  Check,
  Palette
} from 'lucide-react';
import { useEditor } from '@/contexts/EditorContext';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import {
  DropdownMenu,
  DropdownMenuContent,
  DropdownMenuItem,
  DropdownMenuTrigger,
} from '@/components/ui/dropdown-menu';
import {
  Tooltip,
  TooltipContent,
  TooltipTrigger,
} from '@/components/ui/tooltip';
import { cn } from '@/lib/utils';
import { DeviceType, PageType } from '@/types/editor';

const pages: { value: PageType; label: string }[] = [
  { value: 'home', label: 'Home' },
  { value: 'collection', label: 'Collection' },
  { value: 'product', label: 'Product' },
];

const devices: { value: DeviceType; icon: React.ElementType; label: string }[] = [
  { value: 'desktop', icon: Monitor, label: 'Desktop' },
  { value: 'tablet', icon: Tablet, label: 'Tablet' },
  { value: 'mobile', icon: Smartphone, label: 'Mobile' },
];

export function TopBar() {
  const { 
    state, 
    setStoreName, 
    setCurrentPage, 
    setDevice, 
    canUndo, 
    canRedo, 
    undo, 
    redo, 
    save, 
    publish 
  } = useEditor();
  
  const [isEditingName, setIsEditingName] = useState(false);
  const [nameValue, setNameValue] = useState(state.storeName);

  const handleNameSubmit = () => {
    setStoreName(nameValue);
    setIsEditingName(false);
  };

  return (
    <header className="h-14 bg-editor-panel border-b border-editor-border flex items-center px-4 gap-4 shrink-0">
      {/* Left: Logo & Store Name */}
      <div className="flex items-center gap-3 min-w-[200px]">
        <div className="w-8 h-8 rounded-lg bg-primary flex items-center justify-center">
          <Palette className="w-4 h-4 text-primary-foreground" />
        </div>
        
        {isEditingName ? (
          <Input
            value={nameValue}
            onChange={(e) => setNameValue(e.target.value)}
            onBlur={handleNameSubmit}
            onKeyDown={(e) => e.key === 'Enter' && handleNameSubmit()}
            className="h-8 w-40 text-sm font-medium"
            autoFocus
          />
        ) : (
          <button
            onClick={() => setIsEditingName(true)}
            className="text-sm font-medium text-foreground hover:text-primary transition-colors"
          >
            {state.storeName}
          </button>
        )}
      </div>

      {/* Center: Page Selector */}
      <div className="flex-1 flex justify-center">
        <DropdownMenu>
          <DropdownMenuTrigger asChild>
            <Button variant="outline" size="sm" className="gap-2">
              {pages.find((p) => p.value === state.currentPage)?.label}
              <ChevronDown className="w-4 h-4 opacity-50" />
            </Button>
          </DropdownMenuTrigger>
          <DropdownMenuContent align="center" className="bg-popover">
            {pages.map((page) => (
              <DropdownMenuItem
                key={page.value}
                onClick={() => setCurrentPage(page.value)}
                className="gap-2"
              >
                {page.label}
                {state.currentPage === page.value && (
                  <Check className="w-4 h-4 ml-auto" />
                )}
              </DropdownMenuItem>
            ))}
          </DropdownMenuContent>
        </DropdownMenu>
      </div>

      {/* Right: Device Toggles, Undo/Redo, Save/Publish */}
      <div className="flex items-center gap-2 min-w-[200px] justify-end">
        {/* Device Toggles */}
        <div className="flex items-center bg-secondary rounded-lg p-1 gap-0.5">
          {devices.map(({ value, icon: Icon, label }) => (
            <Tooltip key={value}>
              <TooltipTrigger asChild>
                <button
                  onClick={() => setDevice(value)}
                  className={cn(
                    'p-1.5 rounded-md transition-colors',
                    state.device === value
                      ? 'bg-editor-panel text-foreground shadow-sm'
                      : 'text-muted-foreground hover:text-foreground'
                  )}
                >
                  <Icon className="w-4 h-4" />
                </button>
              </TooltipTrigger>
              <TooltipContent side="bottom">{label}</TooltipContent>
            </Tooltip>
          ))}
        </div>

        <div className="w-px h-6 bg-border mx-1" />

        {/* Undo/Redo */}
        <Tooltip>
          <TooltipTrigger asChild>
            <Button
              variant="ghost"
              size="icon"
              className="h-8 w-8"
              disabled={!canUndo}
              onClick={undo}
            >
              <Undo2 className="w-4 h-4" />
            </Button>
          </TooltipTrigger>
          <TooltipContent side="bottom">Undo</TooltipContent>
        </Tooltip>

        <Tooltip>
          <TooltipTrigger asChild>
            <Button
              variant="ghost"
              size="icon"
              className="h-8 w-8"
              disabled={!canRedo}
              onClick={redo}
            >
              <Redo2 className="w-4 h-4" />
            </Button>
          </TooltipTrigger>
          <TooltipContent side="bottom">Redo</TooltipContent>
        </Tooltip>

        <div className="w-px h-6 bg-border mx-1" />

        {/* Save & Publish */}
        <Button variant="outline" size="sm" onClick={save} className="gap-1.5">
          <Save className="w-4 h-4" />
          Save
        </Button>

        <Button size="sm" onClick={publish} className="gap-1.5 bg-success hover:bg-success/90 text-success-foreground">
          <Rocket className="w-4 h-4" />
          Publish
        </Button>
      </div>
    </header>
  );
}
