// layout/shell/shell.tsx
import { SidebarLeft, TriangleRightMini, XMark } from "@medusajs/icons"
import { IconButton, clx } from "@medusajs/ui"
import { AnimatePresence } from "motion/react"
import { Dialog as RadixDialog } from "radix-ui"
import { PropsWithChildren, ReactNode, useEffect, useState } from "react"
import { useTranslation } from "react-i18next"
import {
  Link,
  Outlet,
  UIMatch,
  useMatches,
  useNavigation,
} from "react-router-dom"

import { KeybindProvider } from "../../../providers/keybind-provider"
import { useGlobalShortcuts } from "../../../providers/keybind-provider/hooks"
import { useSidebar } from "../../../providers/sidebar-provider"
import { ProgressBar } from "../../common/progress-bar"
import { Notifications } from "../notifications"

export const Shell = ({ children }: PropsWithChildren) => {
  const globalShortcuts = useGlobalShortcuts()
  const navigation = useNavigation()

  const loading = navigation.state === "loading"

  return (
    <KeybindProvider shortcuts={globalShortcuts}>
      <div className="relative flex h-screen flex-col items-start overflow-hidden lg:flex-row">
        <NavigationBar loading={loading} />
        <div>
          <MobileSidebarContainer>{children}</MobileSidebarContainer>
          <DesktopSidebarContainer>{children}</DesktopSidebarContainer>
        </div>
        <div className="flex h-screen w-full flex-col">
          <Topbar />
          <main
            className={clx(
              "flex h-full w-full flex-col items-center overflow-y-auto transition-opacity delay-200 duration-200",
              {
                "opacity-25": loading,
              }
            )}
          >
            <Gutter>
              <Outlet />
            </Gutter>
          </main>
        </div>
      </div>
    </KeybindProvider>
  )
}

const NavigationBar = ({ loading }: { loading: boolean }) => {
  const [showBar, setShowBar] = useState(false)

  /**
   * If the loading state is true, we want to show the bar after a short delay.
   * The delay is used to prevent the bar from flashing on quick navigations.
   */
  useEffect(() => {
    let timeout: ReturnType<typeof setTimeout>

    if (loading) {
      timeout = setTimeout(() => {
        setShowBar(true)
      }, 200)
    } else {
      setShowBar(false)
    }

    return () => {
      clearTimeout(timeout)
    }
  }, [loading])

  return (
    <div className="fixed inset-x-0 top-0 z-50 h-1">
      <AnimatePresence>{showBar ? <ProgressBar /> : null}</AnimatePresence>
    </div>
  )
}

const Gutter = ({ children }: PropsWithChildren) => {
  return (
    <div className="flex w-full max-w-[1600px] flex-col gap-y-2 p-3">
      {children}
    </div>
  )
}

const Breadcrumbs = () => {
  const matches = useMatches() as unknown as UIMatch<
    unknown,
    {
      breadcrumb?: (match?: UIMatch) => string | ReactNode
    }
  >[]

  const crumbs = matches
    .filter((match) => match.handle?.breadcrumb)
    .map((match) => {
      const handle = match.handle

      let label: string | ReactNode | undefined = undefined

      try {
        label = handle.breadcrumb?.(match)
      } catch (error) {
        // noop
      }

      if (!label) {
        return null
      }

      return {
        label: label,
        path: match.pathname,
      }
    })
    .filter(Boolean) as { label: string | ReactNode; path: string }[]

  return (
    <ol
      className={clx(
        "text-ui-fg-muted txt-compact-small-plus flex select-none items-center"
      )}
    >
      {crumbs.map((crumb, index) => {
        const isLast = index === crumbs.length - 1
        const isSingle = crumbs.length === 1

        return (
          <li key={index} className={clx("flex items-center")}>
            {!isLast ? (
              <Link
                className="transition-fg hover:text-ui-fg-subtle"
                to={crumb.path}
              >
                {crumb.label}
              </Link>
            ) : (
              <div>
                {!isSingle && <span className="block lg:hidden">...</span>}
                <span
                  key={index}
                  className={clx({
                    "hidden lg:block": !isSingle,
                  })}
                >
                  {crumb.label}
                </span>
              </div>
            )}
            {!isLast && (
              <span className="mx-2">
                <TriangleRightMini className="rtl:rotate-180" />
              </span>
            )}
          </li>
        )
      })}
    </ol>
  )
}

const ToggleSidebar = () => {
  const { toggle } = useSidebar()

  return (
    <div>
      <IconButton
        className="hidden lg:flex"
        variant="transparent"
        onClick={() => toggle("desktop")}
        size="small"
      >
        <SidebarLeft className="text-ui-fg-muted rtl:rotate-180" />
      </IconButton>
      <IconButton
        className="hidden max-lg:flex"
        variant="transparent"
        onClick={() => toggle("mobile")}
        size="small"
      >
        <SidebarLeft className="text-ui-fg-muted rtl:rotate-180" />
      </IconButton>
    </div>
  )
}

const Topbar = () => {
  return (
    <div className="grid w-full grid-cols-2 border-b p-3">
      <div className="flex items-center gap-x-1.5">
        <ToggleSidebar />
        <Breadcrumbs />
      </div>
      <div className="flex items-center justify-end gap-x-3">
        <Notifications />
      </div>
    </div>
  )
}

const DesktopSidebarContainer = ({ children }: PropsWithChildren) => {
  const { desktop } = useSidebar()

  return (
    <div
      className={clx("hidden h-screen w-[220px] border-e", {
        "lg:flex": desktop,
      })}
    >
      {children}
    </div>
  )
}

const MobileSidebarContainer = ({ children }: PropsWithChildren) => {
  const { t } = useTranslation()
  const { mobile, toggle } = useSidebar()

  return (
    <RadixDialog.Root open={mobile} onOpenChange={() => toggle("mobile")}>
      <RadixDialog.Portal>
        <RadixDialog.Overlay
          className={clx(
            "bg-ui-bg-overlay fixed inset-0",
            "data-[state=open]:animate-in data-[state=closed]:animate-out data-[state=closed]:fade-out-0 data-[state=open]:fade-in-0"
          )}
        />
        <RadixDialog.Content
          className={clx(
            "bg-ui-bg-subtle shadow-elevation-modal fixed inset-y-2 start-2 flex w-full max-w-[304px] flex-col overflow-hidden rounded-lg border-r",
            "data-[state=open]:animate-in data-[state=closed]:animate-out data-[state=closed]:fade-out-0 data-[state=open]:fade-in-0 data-[state=closed]:slide-out-to-start-1/2 data-[state=open]:slide-in-from-start-1/2 duration-200"
          )}
        >
          <div className="p-3">
            <RadixDialog.Close asChild>
              <IconButton
                size="small"
                variant="transparent"
                className="text-ui-fg-subtle"
              >
                <XMark />
              </IconButton>
            </RadixDialog.Close>
            <RadixDialog.Title className="sr-only">
              {t("app.nav.accessibility.title")}
            </RadixDialog.Title>
            <RadixDialog.Description className="sr-only">
              {t("app.nav.accessibility.description")}
            </RadixDialog.Description>
          </div>
          {children}
        </RadixDialog.Content>
      </RadixDialog.Portal>
    </RadixDialog.Root>
  )
}

// apps/client/src/app/core/layout/shell/shell.component.ts
import { CommonModule } from '@angular/common';
import { ChangeDetectionStrategy, Component, HostListener, inject, signal } from '@angular/core';
import { NavigationStart, Router, RouterModule } from '@angular/router';
import { filter } from 'rxjs';

import { ButtonModule } from 'primeng/button';
import { DialogModule } from 'primeng/dialog';
import { ProgressBarModule } from 'primeng/progressbar';

import { SidebarService } from './sidebar.service';
import { BreadcrumbsService } from './breadcrumbs.service';
import { NotificationsComponent } from '../notifications/notifications.component';

@Component({
  selector: 'app-shell',
  standalone: true,
  imports: [CommonModule, RouterModule, ButtonModule, DialogModule, ProgressBarModule, NotificationsComponent],
  templateUrl: './shell.component.html',
  changeDetection: ChangeDetectionStrategy.OnPush,
})
export class ShellComponent {
  private readonly router = inject(Router);
  readonly sidebar = inject(SidebarService);
  readonly breadcrumbs = inject(BreadcrumbsService);

  readonly loading = signal(false);

  constructor() {
    this.router.events.pipe(filter((e) => e instanceof NavigationStart)).subscribe(() => {
      this.loading.set(true);
      setTimeout(() => this.loading.set(false), 300);
    });
  }

  toggleDesktop(): void {
    this.sidebar.toggle('desktop');
  }

  toggleMobile(): void {
    this.sidebar.toggle('mobile');
  }

  closeMobile(): void {
    this.sidebar.setMobile(false);
  }

  @HostListener('document:keydown', ['$event'])
  onKeydown(e: KeyboardEvent): void {
    if (e.key === 'Escape' && this.sidebar.mobileOpen()) {
      this.closeMobile();
    }
  }
}

<!-- NavigationBar loading progress (fixed top) -->
<div class="fixed inset-x-0 top-0 z-50 h-1">
  @if (loading()) {
    <p-progressBar mode="indeterminate" [style]="{ height: '4px' }" />
  }
</div>

<div class="relative flex h-screen flex-col items-start overflow-hidden lg:flex-row">
  <div>
    <p-dialog
      [visible]="sidebar.mobileOpen()"
      (visibleChange)="sidebar.setMobile($event)"
      [modal]="true"
      [dismissableMask]="true"
      [draggable]="false"
      [resizable]="false"
      [closable]="false"
      [style]="{ width: '304px', maxWidth: '304px' }"
      [contentStyle]="{ padding: '0' }"
      styleClass="!m-0 !p-0"
      position="left"
    >
      <ng-template pTemplate="header">
        <div class="w-full p-3">
          <button
            pButton
            type="button"
            class="p-button-text p-button-sm"
            icon="pi pi-times"
            aria-label="Close navigation"
            (click)="closeMobile()"
          ></button>
          <span class="sr-only">Navigation</span>
        </div>
      </ng-template>

      <ng-content select="[sidebar]"></ng-content>

    </p-dialog>

    @if (sidebar.desktopOpen()) {
      <div class="hidden h-screen w-[220px] border-e lg:flex">
        <ng-content select="[sidebar]"></ng-content>

      </div>
    }
  </div>

  <div class="flex h-screen w-full flex-col overflow-auto">
    <div class="grid w-full grid-cols-2 border-b p-3">
      <div class="flex items-center gap-x-1.5">
        <div>
          <button
            pButton
            type="button"
            class="hidden p-button-text p-button-sm lg:flex"
            icon="pi pi-bars"
            aria-label="Toggle navigation"
            (click)="toggleDesktop()"
          ></button>

          <button
            pButton
            type="button"
            class="flex p-button-text p-button-sm lg:hidden"
            icon="pi pi-bars"
            aria-label="Open navigation"
            (click)="toggleMobile()"
          ></button>
        </div>

        <ol class="text-ui-fg-muted txt-compact-small-plus flex select-none items-center">
          <ng-container *ngFor="let c of breadcrumbs.crumbs(); let i = index">
            <li class="flex items-center">
              @if (i < breadcrumbs.crumbs().length - 1) {
                <a class="transition-fg hover:text-ui-fg-subtle" [routerLink]="c.path">
                  {{ c.label }}
                </a>
              } @else {
                <div>
                  @if (breadcrumbs.crumbs().length > 1) {
                    <span class="block lg:hidden"> ... </span>
                  }
                  <span
                    class="lg:block"
                    [class.hidden]="breadcrumbs.crumbs().length > 1"
                  >
                    {{ c.label }}
                  </span>
                </div>
              }

              @if (i < breadcrumbs.crumbs().length - 1) {
                <span class="mx-2">
                  <i class="pi pi-angle-right rtl:rotate-180"></i>
                </span>
              }
            </li>
          </ng-container>
        </ol>
      </div>

      <div class="flex items-center justify-end gap-x-3">
        <app-notifications />
      </div>
    </div>

    <main
      class="flex h-full w-full flex-col items-center overflow-y-auto transition-opacity delay-200 duration-200"
      [class.opacity-25]="loading()"
    >
      <div class="flex w-full max-w-[1600px] flex-col gap-y-2 p-3">
        <router-outlet />
      </div>
    </main>
  </div>
</div>
