// visual-website-builder-main/src/components/editor/InspectorPanel.tsx
import { useState, useMemo } from 'react';
import { RotateCcw, ChevronDown, ChevronRight, Image as ImageIcon, X } from 'lucide-react';
import { useEditor } from '@/contexts/EditorContext';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { Textarea } from '@/components/ui/textarea';
import { Switch } from '@/components/ui/switch';
import { Slider } from '@/components/ui/slider';
import { Label } from '@/components/ui/label';
import { ScrollArea } from '@/components/ui/scroll-area';
import {
  Select,
  SelectContent,
  SelectItem,
  SelectTrigger,
  SelectValue,
} from '@/components/ui/select';
import {
  Collapsible,
  CollapsibleContent,
  CollapsibleTrigger,
} from '@/components/ui/collapsible';
import { cn } from '@/lib/utils';
import { sectionDefinitions, mockCollections } from '@/data/mockData';
import { SettingField, Collection } from '@/types/editor';

interface FieldProps {
  field: SettingField;
  value: unknown;
  onChange: (value: unknown) => void;
}

function TextField({ field, value, onChange }: FieldProps) {
  return (
    <div className="space-y-2">
      <Label className="text-sm">{field.label}</Label>
      <Input
        value={(value as string) || ''}
        onChange={(e) => onChange(e.target.value)}
        placeholder={field.label}
      />
      {field.description && (
        <p className="text-xs text-muted-foreground">{field.description}</p>
      )}
    </div>
  );
}

function TextareaField({ field, value, onChange }: FieldProps) {
  const text = (value as string) || '';
  return (
    <div className="space-y-2">
      <div className="flex items-center justify-between">
        <Label className="text-sm">{field.label}</Label>
        <span className="text-xs text-muted-foreground">{text.length} characters</span>
      </div>
      <Textarea
        value={text}
        onChange={(e) => onChange(e.target.value)}
        placeholder={field.label}
        rows={3}
      />
    </div>
  );
}

function ToggleField({ field, value, onChange }: FieldProps) {
  return (
    <div className="flex items-center justify-between py-1">
      <div>
        <Label className="text-sm">{field.label}</Label>
        {field.description && (
          <p className="text-xs text-muted-foreground">{field.description}</p>
        )}
      </div>
      <Switch
        checked={Boolean(value)}
        onCheckedChange={onChange}
      />
    </div>
  );
}

function SelectField({ field, value, onChange }: FieldProps) {
  return (
    <div className="space-y-2">
      <Label className="text-sm">{field.label}</Label>
      <Select value={(value as string) || ''} onValueChange={onChange}>
        <SelectTrigger className="bg-background">
          <SelectValue placeholder={`Select ${field.label.toLowerCase()}`} />
        </SelectTrigger>
        <SelectContent className="bg-popover">
          {field.options?.map((option) => (
            <SelectItem key={option.value} value={option.value}>
              {option.label}
            </SelectItem>
          ))}
        </SelectContent>
      </Select>
    </div>
  );
}

function ColorField({ field, value, onChange }: FieldProps) {
  const presetColors = [
    '#6366F1', '#8B5CF6', '#EC4899', '#EF4444', '#F97316',
    '#EAB308', '#22C55E', '#14B8A6', '#3B82F6', '#1F2937',
    '#FFFFFF', '#F8FAFC',
  ];

  return (
    <div className="space-y-2">
      <Label className="text-sm">{field.label}</Label>
      <div className="flex items-center gap-2">
        <div
          className="w-10 h-10 rounded-lg border cursor-pointer"
          style={{ backgroundColor: (value as string) || '#FFFFFF' }}
        >
          <input
            type="color"
            value={(value as string) || '#FFFFFF'}
            onChange={(e) => onChange(e.target.value)}
            className="w-full h-full opacity-0 cursor-pointer"
          />
        </div>
        <Input
          value={(value as string) || ''}
          onChange={(e) => onChange(e.target.value)}
          placeholder="#FFFFFF"
          className="flex-1 font-mono text-sm"
        />
      </div>
      <div className="flex flex-wrap gap-1.5">
        {presetColors.map((color) => (
          <button
            key={color}
            onClick={() => onChange(color)}
            className={cn(
              'w-6 h-6 rounded border transition-transform hover:scale-110',
              value === color && 'ring-2 ring-primary ring-offset-2'
            )}
            style={{ backgroundColor: color }}
          />
        ))}
      </div>
    </div>
  );
}

function RangeField({ field, value, onChange }: FieldProps) {
  const numValue = (value as number) || field.min || 0;
  return (
    <div className="space-y-3">
      <div className="flex items-center justify-between">
        <Label className="text-sm">{field.label}</Label>
        <span className="text-sm font-medium tabular-nums">{numValue}</span>
      </div>
      <Slider
        value={[numValue]}
        onValueChange={([v]) => onChange(v)}
        min={field.min || 0}
        max={field.max || 100}
        step={field.step || 1}
      />
    </div>
  );
}

function ImageField({ field, value, onChange }: FieldProps) {
  const hasImage = Boolean(value);
  
  return (
    <div className="space-y-2">
      <Label className="text-sm">{field.label}</Label>
      {hasImage ? (
        <div className="relative aspect-video bg-muted rounded-lg overflow-hidden group">
          <div className="absolute inset-0 flex items-center justify-center text-muted-foreground">
            <ImageIcon className="w-8 h-8" />
          </div>
          <button
            onClick={() => onChange(null)}
            className="absolute top-2 right-2 p-1.5 bg-background/80 rounded-full opacity-0 group-hover:opacity-100 transition-opacity hover:bg-destructive hover:text-destructive-foreground"
          >
            <X className="w-4 h-4" />
          </button>
        </div>
      ) : (
        <button
          onClick={() => onChange('placeholder-image')}
          className="w-full aspect-video border-2 border-dashed rounded-lg flex flex-col items-center justify-center gap-2 text-muted-foreground hover:border-primary hover:text-primary transition-colors"
        >
          <ImageIcon className="w-8 h-8" />
          <span className="text-sm">Click to upload</span>
        </button>
      )}
    </div>
  );
}

function CollectionField({ field, value, onChange }: FieldProps) {
  const [isOpen, setIsOpen] = useState(false);
  const [search, setSearch] = useState('');
  
  const selectedCollection = mockCollections.find((c) => c.id === value);
  const filteredCollections = mockCollections.filter((c) =>
    c.name.toLowerCase().includes(search.toLowerCase())
  );

  return (
    <div className="space-y-2">
      <Label className="text-sm">{field.label}</Label>
      {selectedCollection ? (
        <div className="flex items-center gap-3 p-3 bg-muted rounded-lg">
          <div className="w-12 h-12 bg-muted-foreground/20 rounded-lg flex items-center justify-center">
            <ImageIcon className="w-5 h-5 text-muted-foreground" />
          </div>
          <div className="flex-1 min-w-0">
            <p className="font-medium text-sm truncate">{selectedCollection.name}</p>
            <p className="text-xs text-muted-foreground">{selectedCollection.productCount} products</p>
          </div>
          <Button variant="ghost" size="sm" onClick={() => onChange(null)}>
            <X className="w-4 h-4" />
          </Button>
        </div>
      ) : (
        <Collapsible open={isOpen} onOpenChange={setIsOpen}>
          <CollapsibleTrigger asChild>
            <Button variant="outline" className="w-full justify-between">
              Select collection
              <ChevronDown className={cn('w-4 h-4 transition-transform', isOpen && 'rotate-180')} />
            </Button>
          </CollapsibleTrigger>
          <CollapsibleContent className="mt-2 space-y-2">
            <Input
              placeholder="Search collections..."
              value={search}
              onChange={(e) => setSearch(e.target.value)}
            />
            <div className="grid grid-cols-2 gap-2 max-h-48 overflow-auto">
              {filteredCollections.map((collection) => (
                <button
                  key={collection.id}
                  onClick={() => {
                    onChange(collection.id);
                    setIsOpen(false);
                  }}
                  className="p-3 bg-muted rounded-lg hover:bg-accent transition-colors text-left"
                >
                  <div className="w-full aspect-square bg-muted-foreground/20 rounded-lg mb-2 flex items-center justify-center">
                    <ImageIcon className="w-6 h-6 text-muted-foreground" />
                  </div>
                  <p className="font-medium text-sm truncate">{collection.name}</p>
                  <p className="text-xs text-muted-foreground">{collection.productCount} products</p>
                </button>
              ))}
            </div>
          </CollapsibleContent>
        </Collapsible>
      )}
    </div>
  );
}

function SettingFieldRenderer({ field, value, onChange }: FieldProps) {
  switch (field.type) {
    case 'text':
      return <TextField field={field} value={value} onChange={onChange} />;
    case 'textarea':
      return <TextareaField field={field} value={value} onChange={onChange} />;
    case 'toggle':
      return <ToggleField field={field} value={value} onChange={onChange} />;
    case 'select':
      return <SelectField field={field} value={value} onChange={onChange} />;
    case 'color':
      return <ColorField field={field} value={value} onChange={onChange} />;
    case 'range':
      return <RangeField field={field} value={value} onChange={onChange} />;
    case 'image':
      return <ImageField field={field} value={value} onChange={onChange} />;
    case 'collection':
      return <CollectionField field={field} value={value} onChange={onChange} />;
    default:
      return null;
  }
}

export function InspectorPanel() {
  const { selectedSection, updateSectionSettings } = useEditor();
  const [openGroups, setOpenGroups] = useState<Record<string, boolean>>({
    Content: true,
    Layout: true,
    Style: true,
  });

  const sectionDef = useMemo(() => {
    if (!selectedSection) return null;
    return sectionDefinitions.find((d) => d.type === selectedSection.type);
  }, [selectedSection]);

  const groupedFields = useMemo(() => {
    if (!sectionDef) return {};
    return sectionDef.settingsSchema.reduce((acc, field) => {
      const group = field.group || 'General';
      if (!acc[group]) acc[group] = [];
      acc[group].push(field);
      return acc;
    }, {} as Record<string, SettingField[]>);
  }, [sectionDef]);

  const handleChange = (key: string, value: unknown) => {
    if (selectedSection) {
      updateSectionSettings(selectedSection.id, { [key]: value });
    }
  };

  const toggleGroup = (group: string) => {
    setOpenGroups((prev) => ({ ...prev, [group]: !prev[group] }));
  };

  if (!selectedSection) {
    return (
      <div className="w-[320px] bg-editor-panel border-l border-editor-border flex flex-col h-full">
        <div className="flex-1 flex items-center justify-center p-8">
          <div className="text-center text-muted-foreground">
            <p className="font-medium mb-1">No section selected</p>
            <p className="text-sm">Click on a section in the preview or left panel to edit its settings</p>
          </div>
        </div>
      </div>
    );
  }

  return (
    <div className="w-[320px] bg-editor-panel border-l border-editor-border flex flex-col h-full">
      {/* Header */}
      <div className="px-4 py-3 border-b border-editor-border">
        <h2 className="text-sm font-semibold text-foreground">{selectedSection.name}</h2>
        <p className="text-xs text-muted-foreground capitalize">{selectedSection.type.replace(/-/g, ' ')}</p>
      </div>

      {/* Settings */}
      <ScrollArea className="flex-1">
        <div className="p-4 space-y-4">
          {Object.entries(groupedFields).map(([group, fields]) => (
            <Collapsible
              key={group}
              open={openGroups[group] !== false}
              onOpenChange={() => toggleGroup(group)}
            >
              <CollapsibleTrigger className="flex items-center justify-between w-full py-2 text-sm font-medium hover:text-primary transition-colors">
                {group}
                {openGroups[group] !== false ? (
                  <ChevronDown className="w-4 h-4" />
                ) : (
                  <ChevronRight className="w-4 h-4" />
                )}
              </CollapsibleTrigger>
              <CollapsibleContent className="space-y-4 pt-2">
                {fields.map((field) => (
                  <SettingFieldRenderer
                    key={field.key}
                    field={field}
                    value={selectedSection.settings[field.key]}
                    onChange={(value) => handleChange(field.key, value)}
                  />
                ))}
              </CollapsibleContent>
            </Collapsible>
          ))}
        </div>
      </ScrollArea>

      {/* Footer */}
      <div className="p-4 border-t border-editor-border">
        <Button variant="outline" size="sm" className="w-full gap-2 text-muted-foreground hover:text-foreground">
          <RotateCcw className="w-4 h-4" />
          Reset Section
        </Button>
      </div>
    </div>
  );
}

// libs/cms/ui/src/lib/editor/inspector-panel.component.ts
import {
  ChangeDetectionStrategy,
  Component,
  EventEmitter,
  Input,
  OnChanges,
  Output,
  SimpleChanges,
} from '@angular/core';
import { Collection, Section, SectionDefinition, SettingField } from '@flex-erp/types';
import { CmsButtonComponent } from '../primitives/button/cms-button.component';
import { CmsInputComponent } from '../primitives/input/cms-input.component';
import { CmsTextareaComponent } from '../primitives/textarea/cms-textarea.component';
import { CmsSwitchComponent } from '../primitives/switch/cms-switch.component';
import { CmsSliderComponent } from '../primitives/slider/cms-slider.component';
import { CmsSelectComponent } from '../primitives/select/cms-select.component';
import { CmsScrollAreaComponent } from '../primitives/scroll-area/cms-scroll-area.component';
import { RdxCollapsibleModule } from '@radix-ng/primitives/collapsible';

@Component({
  selector: 'cms-inspector-panel',
  standalone: true,
  imports: [
    CmsButtonComponent,
    CmsInputComponent,
    CmsTextareaComponent,
    CmsSwitchComponent,
    CmsSliderComponent,
    CmsSelectComponent,
    CmsScrollAreaComponent,
    RdxCollapsibleModule,
  ],
  templateUrl: './inspector-panel.component.html',
  changeDetection: ChangeDetectionStrategy.OnPush,
})
export class CmsInspectorPanelComponent implements OnChanges {
  @Input() selectedSection: Section | null = null;
  @Input() sectionDefinitions: SectionDefinition[] = [];
  @Input() collections: Collection[] = [];

  @Output() updateSectionSettings = new EventEmitter<{ sectionId: string; key: string; value: unknown }>();

  sectionDefinition: SectionDefinition | null = null;
  groupedFields: Record<string, SettingField[]> = {};
  groupEntries: Array<{ key: string; value: SettingField[] }> = [];
  openGroups: Record<string, boolean> = {
    Content: true,
    Layout: true,
    Style: true,
  };

  collectionOpen = false;
  collectionSearch = '';

  readonly presetColors = [
    '#6366F1',
    '#8B5CF6',
    '#EC4899',
    '#EF4444',
    '#F97316',
    '#EAB308',
    '#22C55E',
    '#14B8A6',
    '#3B82F6',
    '#1F2937',
    '#FFFFFF',
    '#F8FAFC',
  ];

  ngOnChanges(changes: SimpleChanges): void {
    if (changes['selectedSection'] || changes['sectionDefinitions']) {
      this.sectionDefinition = this.resolveSectionDefinition();
      this.groupedFields = this.groupFields(this.sectionDefinition);
      this.groupEntries = Object.entries(this.groupedFields).map(([key, value]) => ({ key, value }));
    }
  }

  resolveSectionDefinition(): SectionDefinition | null {
    if (!this.selectedSection) return null;
    return this.sectionDefinitions.find((def) => def.type === this.selectedSection?.type) ?? null;
  }

  groupFields(definition: SectionDefinition | null): Record<string, SettingField[]> {
    if (!definition) return {};
    return definition.settingsSchema.reduce((acc, field) => {
      const group = field.group || 'General';
      if (!acc[group]) acc[group] = [];
      acc[group].push(field);
      return acc;
    }, {} as Record<string, SettingField[]>);
  }

  toggleGroup(group: string): void {
    this.openGroups[group] = !this.openGroups[group];
  }

  updateSetting(key: string, value: unknown): void {
    if (!this.selectedSection) return;
    this.updateSectionSettings.emit({
      sectionId: this.selectedSection.id,
      key,
      value,
    });
  }

  toNumber(value: unknown, fallback: number): number {
    const num = Number(value);
    return Number.isNaN(num) ? fallback : num;
  }

  selectedCollection(): Collection | null {
    if (!this.selectedSection) return null;
    const value = this.selectedSection.settings['collection'];
    return this.collections.find((c) => c.id === value) ?? null;
  }

  filteredCollections(): Collection[] {
    const search = this.collectionSearch.toLowerCase();
    return this.collections.filter((collection) => collection.name.toLowerCase().includes(search));
  }

  clearCollection(): void {
    this.updateSetting('collection', null);
  }

  selectCollection(collectionId: string): void {
    this.updateSetting('collection', collectionId);
    this.collectionOpen = false;
  }
}

<div class="w-[320px] bg-ui-bg-base border-l border-ui-border-base flex flex-col h-full">
  @if (!selectedSection) {
    <div class="flex-1 flex items-center justify-center p-8">
      <div class="text-center text-ui-fg-muted">
        <p class="font-medium mb-1">No section selected</p>
        <p class="text-sm">Click on a section in the preview or left panel to edit its settings</p>
      </div>
    </div>
  } @else {
    <div class="px-4 py-3 border-b border-ui-border-base">
      <h2 class="text-sm font-semibold text-ui-fg-base">{{ selectedSection.name }}</h2>
      <p class="text-xs text-ui-fg-muted capitalize">{{ selectedSection.type.replace('-', ' ') }}</p>
    </div>

    <cms-scroll-area className="flex-1">
      <div class="p-4 space-y-4">
        @for (group of groupEntries; track group.key) {
          <div
            rdxCollapsibleRoot
            [open]="openGroups[group.key] !== false"
            (openChange)="toggleGroup(group.key)"
          >
            <button
              rdxCollapsibleTrigger
              type="button"
              class="flex items-center justify-between w-full py-2 text-sm font-medium hover:text-ui-fg-base transition-colors"
            >
              {{ group.key }}
              @if (openGroups[group.key] !== false) {
                <i class="pi pi-chevron-down text-xs"></i>
              } @else {
                <i class="pi pi-chevron-right text-xs"></i>
              }
            </button>

            <div rdxCollapsibleContent class="space-y-4 pt-2">
              @for (field of group.value; track field.key) {
                @switch (field.type) {
                  @case ('text') {
                    <div class="space-y-2">
                      <span class="text-sm">{{ field.label }}</span>
                      <cms-input
                        [value]="$any(selectedSection.settings[field.key])"
                        (valueChange)="updateSetting(field.key, $event)"
                        [placeholder]="field.label"
                      ></cms-input>
                      @if (field.description) {
                        <p class="text-xs text-ui-fg-muted">{{ field.description }}</p>
                      }
                    </div>
                  }
                  @case ('textarea') {
                    <div class="space-y-2">
                      <div class="flex items-center justify-between">
                        <span class="text-sm">{{ field.label }}</span>
                        <span class="text-xs text-ui-fg-muted">{{ ($any(selectedSection.settings[field.key]) || '').length }} characters</span>
                      </div>
                      <cms-textarea
                        [value]="$any(selectedSection.settings[field.key])"
                        (valueChange)="updateSetting(field.key, $event)"
                        [placeholder]="field.label"
                        [rows]="3"
                      ></cms-textarea>
                    </div>
                  }
                  @case ('toggle') {
                    <div class="flex items-center justify-between py-1">
                      <div>
                        <span class="text-sm">{{ field.label }}</span>
                        @if (field.description) {
                          <p class="text-xs text-ui-fg-muted">{{ field.description }}</p>
                        }
                      </div>
                      <cms-switch
                        [checked]="!!selectedSection.settings[field.key]"
                        (checkedChange)="updateSetting(field.key, $event)"
                      ></cms-switch>
                    </div>
                  }
                  @case ('select') {
                    <div class="space-y-2">
                      <span class="text-sm">{{ field.label }}</span>
                      <cms-select
                        [value]="$any(selectedSection.settings[field.key])"
                        (valueChange)="updateSetting(field.key, $event)"
                        [placeholder]="'Select ' + field.label.toLowerCase()"
                        [options]="field.options || []"
                      ></cms-select>
                    </div>
                  }
                  @case ('color') {
                    <div class="space-y-2">
                      <span class="text-sm">{{ field.label }}</span>
                      <div class="flex items-center gap-2">
                        <div
                          class="w-10 h-10 rounded-lg border border-ui-border-base cursor-pointer"
                          [style.backgroundColor]="selectedSection.settings[field.key] || '#FFFFFF'"
                        >
                          <input
                            type="color"
                            [value]="$any(selectedSection.settings[field.key]) || '#FFFFFF'"
                            (input)="updateSetting(field.key, $any($event.target).value)"
                            class="w-full h-full opacity-0 cursor-pointer"
                          />
                        </div>
                        <cms-input
                          [value]="$any(selectedSection.settings[field.key])"
                          (valueChange)="updateSetting(field.key, $event)"
                          placeholder="#FFFFFF"
                          className="flex-1 font-mono text-sm"
                        ></cms-input>
                      </div>
                      <div class="flex flex-wrap gap-1.5">
                        @for (color of presetColors; track color) {
                          <button
                            type="button"
                            (click)="updateSetting(field.key, color)"
                            class="w-6 h-6 rounded border border-ui-border-base transition-transform hover:scale-110"
                            [class.ring-2]="selectedSection.settings[field.key] === color"
                            [class.ring-ui-border-interactive]="selectedSection.settings[field.key] === color"
                            [style.backgroundColor]="color"
                          >
                            <span class="sr-only">Select color {{ color }}</span>
                          </button>
                        }
                      </div>
                    </div>
                  }
                  @case ('range') {
                    <div class="space-y-3">
                      <div class="flex items-center justify-between">
                        <span class="text-sm">{{ field.label }}</span>
                        <span class="text-sm font-medium tabular-nums">{{ selectedSection.settings[field.key] || field.min || 0 }}</span>
                      </div>
                      <cms-slider
                        [value]="toNumber($any(selectedSection.settings[field.key]), field.min || 0)"
                        (valueChange)="updateSetting(field.key, $event)"
                        [min]="field.min || 0"
                        [max]="field.max || 100"
                        [step]="field.step || 1"
                      ></cms-slider>
                    </div>
                  }
                  @case ('image') {
                    <div class="space-y-2">
                      <span class="text-sm">{{ field.label }}</span>
                      @if (selectedSection.settings[field.key]) {
                        <div class="relative aspect-video bg-ui-bg-subtle rounded-lg overflow-hidden group">
                          <div class="absolute inset-0 flex items-center justify-center text-ui-fg-muted">
                            <i class="pi pi-image text-2xl"></i>
                          </div>
                          <button
                            type="button"
                            (click)="updateSetting(field.key, null)"
                            class="absolute top-2 right-2 p-1.5 bg-ui-bg-base/80 rounded-full opacity-0 group-hover:opacity-100 transition-opacity hover:bg-ui-button-danger hover:text-ui-fg-on-color"
                          >
                            <i class="pi pi-times text-xs"></i>
                          </button>
                        </div>
                      } @else {
                        <button
                          type="button"
                          (click)="updateSetting(field.key, 'placeholder-image')"
                          class="w-full aspect-video border-2 border-dashed rounded-lg flex flex-col items-center justify-center gap-2 text-ui-fg-muted hover:border-ui-border-interactive hover:text-ui-fg-base transition-colors"
                        >
                          <i class="pi pi-image text-2xl"></i>
                          <span class="text-sm">Click to upload</span>
                        </button>
                      }
                    </div>
                  }
                  @case ('collection') {
                    <div class="space-y-2">
                      <span class="text-sm">{{ field.label }}</span>
                      @if (selectedCollection()) {
                        <div class="flex items-center gap-3 p-3 bg-ui-bg-subtle rounded-lg">
                          <div class="w-12 h-12 bg-ui-bg-field rounded-lg flex items-center justify-center">
                            <i class="pi pi-image text-ui-fg-muted"></i>
                          </div>
                          <div class="flex-1 min-w-0">
                            <p class="font-medium text-sm truncate">{{ selectedCollection()?.name }}</p>
                            <p class="text-xs text-ui-fg-muted">{{ selectedCollection()?.productCount }} products</p>
                          </div>
                          <cms-button variant="ghost" size="sm" (click)="clearCollection()">
                            <i class="pi pi-times text-sm"></i>
                          </cms-button>
                        </div>
                      } @else {
                        <cms-button
                          variant="outline"
                          className="w-full justify-between"
                          (click)="collectionOpen = !collectionOpen"
                        >
                          Select collection
                          <i class="pi pi-chevron-down text-xs" [class.rotate-180]="collectionOpen"></i>
                        </cms-button>
                        @if (collectionOpen) {
                          <div class="mt-2 space-y-2">
                            <cms-input
                              placeholder="Search collections..."
                              [value]="collectionSearch"
                              (valueChange)="collectionSearch = $event"
                            ></cms-input>
                            <div class="grid grid-cols-2 gap-2 max-h-48 overflow-auto">
                              @for (collection of filteredCollections(); track collection.id) {
                                <button
                                  type="button"
                                  (click)="selectCollection(collection.id)"
                                  class="p-3 bg-ui-bg-subtle rounded-lg hover:bg-ui-bg-subtle-hover transition-colors text-left"
                                >
                                  <div class="w-full aspect-square bg-ui-bg-field rounded-lg mb-2 flex items-center justify-center">
                                    <i class="pi pi-image text-ui-fg-muted"></i>
                                  </div>
                                  <p class="font-medium text-sm truncate">{{ collection.name }}</p>
                                  <p class="text-xs text-ui-fg-muted">{{ collection.productCount }} products</p>
                                </button>
                              }
                            </div>
                          </div>
                        }
                      }
                    </div>
                  }
                }
              }
            </div>
          </div>
        }
      </div>
    </cms-scroll-area>

    <div class="p-4 border-t border-ui-border-base">
      <cms-button variant="outline" size="sm" className="w-full gap-2 text-ui-fg-muted hover:text-ui-fg-base">
        <i class="pi pi-refresh text-sm"></i>
        Reset Section
      </cms-button>
    </div>
  }
</div>
