// visual-website-builder-main/src/components/editor/SectionsTree.tsx
import { useState } from 'react';
import { 
  GripVertical, 
  Eye, 
  EyeOff, 
  Copy, 
  Trash2, 
  ChevronRight, 
  Plus,
  LayoutTemplate,
  Image,
  Columns,
  Grid3X3,
  Mail,
  PanelBottom,
  Megaphone,
  CreditCard,
  Quote,
  FolderKanban
} from 'lucide-react';
import { useEditor } from '@/contexts/EditorContext';
import { Button } from '@/components/ui/button';
import { ScrollArea } from '@/components/ui/scroll-area';
import {
  AlertDialog,
  AlertDialogAction,
  AlertDialogCancel,
  AlertDialogContent,
  AlertDialogDescription,
  AlertDialogFooter,
  AlertDialogHeader,
  AlertDialogTitle,
} from '@/components/ui/alert-dialog';
import { cn } from '@/lib/utils';
import { Section, Block } from '@/types/editor';

const iconMap: Record<string, React.ElementType> = {
  'layout-template': LayoutTemplate,
  'image': Image,
  'columns': Columns,
  'grid-3x3': Grid3X3,
  'mail': Mail,
  'panel-bottom': PanelBottom,
  'megaphone': Megaphone,
  'credit-card': CreditCard,
  'quote': Quote,
  'folder-kanban': FolderKanban,
};

interface SectionItemProps {
  section: Section;
  isSelected: boolean;
  onSelect: () => void;
  onToggleVisibility: () => void;
  onDuplicate: () => void;
  onDelete: () => void;
  onDragStart: (e: React.DragEvent, index: number) => void;
  onDragOver: (e: React.DragEvent) => void;
  onDrop: (e: React.DragEvent, index: number) => void;
  index: number;
  isDragOver: boolean;
}

function SectionItem({
  section,
  isSelected,
  onSelect,
  onToggleVisibility,
  onDuplicate,
  onDelete,
  onDragStart,
  onDragOver,
  onDrop,
  index,
  isDragOver,
}: SectionItemProps) {
  const [isExpanded, setIsExpanded] = useState(false);
  const [showDeleteDialog, setShowDeleteDialog] = useState(false);
  const Icon = iconMap[section.icon] || LayoutTemplate;

  const hasBlocks = section.blocks.length > 0;

  return (
    <>
      <div
        className={cn(
          'relative',
          isDragOver && 'before:absolute before:inset-x-0 before:top-0 before:h-0.5 before:bg-primary before:z-10'
        )}
        onDragOver={onDragOver}
        onDrop={(e) => onDrop(e, index)}
      >
        <div
          className={cn(
            'group flex items-center gap-2 px-3 py-2.5 cursor-pointer transition-colors border-l-2',
            isSelected
              ? 'bg-editor-selected border-l-editor-selected-border'
              : 'border-l-transparent hover:bg-editor-hover',
            !section.visible && 'opacity-50'
          )}
          onClick={onSelect}
          draggable
          onDragStart={(e) => onDragStart(e, index)}
        >
          {/* Drag Handle */}
          <button
            className="p-0.5 -ml-1 cursor-grab active:cursor-grabbing opacity-0 group-hover:opacity-100 transition-opacity text-muted-foreground hover:text-foreground"
            onMouseDown={(e) => e.stopPropagation()}
          >
            <GripVertical className="w-4 h-4" />
          </button>

          {/* Expand Arrow (if has blocks) */}
          {hasBlocks ? (
            <button
              onClick={(e) => {
                e.stopPropagation();
                setIsExpanded(!isExpanded);
              }}
              className="p-0.5 text-muted-foreground hover:text-foreground transition-colors"
            >
              <ChevronRight
                className={cn('w-4 h-4 transition-transform', isExpanded && 'rotate-90')}
              />
            </button>
          ) : (
            <div className="w-5" />
          )}

          {/* Icon */}
          <Icon className="w-4 h-4 text-muted-foreground shrink-0" />

          {/* Name */}
          <span className="text-sm font-medium truncate flex-1">{section.name}</span>

          {/* Hover Actions */}
          <div className="flex items-center gap-0.5 opacity-0 group-hover:opacity-100 transition-opacity">
            <button
              onClick={(e) => {
                e.stopPropagation();
                onToggleVisibility();
              }}
              className="p-1.5 rounded hover:bg-accent text-muted-foreground hover:text-foreground transition-colors"
            >
              {section.visible ? <Eye className="w-3.5 h-3.5" /> : <EyeOff className="w-3.5 h-3.5" />}
            </button>
            <button
              onClick={(e) => {
                e.stopPropagation();
                onDuplicate();
              }}
              className="p-1.5 rounded hover:bg-accent text-muted-foreground hover:text-foreground transition-colors"
            >
              <Copy className="w-3.5 h-3.5" />
            </button>
            <button
              onClick={(e) => {
                e.stopPropagation();
                setShowDeleteDialog(true);
              }}
              className="p-1.5 rounded hover:bg-destructive/10 text-muted-foreground hover:text-destructive transition-colors"
            >
              <Trash2 className="w-3.5 h-3.5" />
            </button>
          </div>
        </div>

        {/* Nested Blocks */}
        {hasBlocks && isExpanded && (
          <div className="ml-8 border-l border-editor-border">
            {section.blocks.map((block) => (
              <BlockItem key={block.id} block={block} sectionId={section.id} />
            ))}
          </div>
        )}
      </div>

      <AlertDialog open={showDeleteDialog} onOpenChange={setShowDeleteDialog}>
        <AlertDialogContent>
          <AlertDialogHeader>
            <AlertDialogTitle>Delete Section</AlertDialogTitle>
            <AlertDialogDescription>
              Are you sure you want to delete "{section.name}"? This action cannot be undone.
            </AlertDialogDescription>
          </AlertDialogHeader>
          <AlertDialogFooter>
            <AlertDialogCancel>Cancel</AlertDialogCancel>
            <AlertDialogAction
              onClick={onDelete}
              className="bg-destructive text-destructive-foreground hover:bg-destructive/90"
            >
              Delete
            </AlertDialogAction>
          </AlertDialogFooter>
        </AlertDialogContent>
      </AlertDialog>
    </>
  );
}

function BlockItem({ block, sectionId }: { block: Block; sectionId: string }) {
  const { state, selectSection } = useEditor();
  const isSelected = state.selectedSectionId === sectionId && state.selectedBlockId === block.id;

  return (
    <div
      className={cn(
        'flex items-center gap-2 px-3 py-2 cursor-pointer transition-colors border-l-2',
        isSelected
          ? 'bg-editor-selected border-l-editor-selected-border'
          : 'border-l-transparent hover:bg-editor-hover'
      )}
      onClick={() => selectSection(sectionId, block.id)}
    >
      <div className="w-1.5 h-1.5 rounded-full bg-muted-foreground" />
      <span className="text-sm text-muted-foreground">{block.name}</span>
    </div>
  );
}

interface SectionsTreeProps {
  onAddSection: () => void;
}

export function SectionsTree({ onAddSection }: SectionsTreeProps) {
  const { state, selectSection, toggleSectionVisibility, duplicateSection, deleteSection, reorderSections } = useEditor();
  const [dragOverIndex, setDragOverIndex] = useState<number | null>(null);
  const [draggedIndex, setDraggedIndex] = useState<number | null>(null);

  const handleDragStart = (e: React.DragEvent, index: number) => {
    setDraggedIndex(index);
    e.dataTransfer.effectAllowed = 'move';
    e.dataTransfer.setData('text/plain', index.toString());
  };

  const handleDragOver = (e: React.DragEvent) => {
    e.preventDefault();
    e.dataTransfer.dropEffect = 'move';
  };

  const handleDragEnter = (index: number) => {
    if (draggedIndex !== null && draggedIndex !== index) {
      setDragOverIndex(index);
    }
  };

  const handleDrop = (e: React.DragEvent, targetIndex: number) => {
    e.preventDefault();
    const sourceIndex = parseInt(e.dataTransfer.getData('text/plain'));
    if (sourceIndex !== targetIndex) {
      reorderSections(sourceIndex, targetIndex);
    }
    setDragOverIndex(null);
    setDraggedIndex(null);
  };

  const handleDragEnd = () => {
    setDragOverIndex(null);
    setDraggedIndex(null);
  };

  return (
    <div className="w-[280px] bg-editor-panel border-r border-editor-border flex flex-col h-full">
      {/* Header */}
      <div className="px-4 py-3 border-b border-editor-border">
        <h2 className="text-sm font-semibold text-foreground">Sections</h2>
        <p className="text-xs text-muted-foreground mt-0.5">Drag to reorder</p>
      </div>

      {/* Sections List */}
      <ScrollArea className="flex-1">
        <div className="py-2" onDragEnd={handleDragEnd}>
          {state.sections.length === 0 ? (
            <div className="px-4 py-8 text-center">
              <p className="text-sm text-muted-foreground">No sections yet</p>
              <p className="text-xs text-muted-foreground mt-1">Click below to add your first section</p>
            </div>
          ) : (
            state.sections.map((section, index) => (
              <div
                key={section.id}
                onDragEnter={() => handleDragEnter(index)}
              >
                <SectionItem
                  section={section}
                  isSelected={state.selectedSectionId === section.id}
                  onSelect={() => selectSection(section.id)}
                  onToggleVisibility={() => toggleSectionVisibility(section.id)}
                  onDuplicate={() => duplicateSection(section.id)}
                  onDelete={() => deleteSection(section.id)}
                  onDragStart={handleDragStart}
                  onDragOver={handleDragOver}
                  onDrop={handleDrop}
                  index={index}
                  isDragOver={dragOverIndex === index}
                />
              </div>
            ))
          )}
        </div>
      </ScrollArea>

      {/* Add Section Button */}
      <div className="p-4 border-t border-editor-border">
        <Button onClick={onAddSection} variant="outline" className="w-full gap-2">
          <Plus className="w-4 h-4" />
          Add Section
        </Button>
      </div>
    </div>
  );
}

// libs/cms/ui/src/lib/editor/sections-tree.component.ts
import { ChangeDetectionStrategy, Component, EventEmitter, Input, Output } from '@angular/core';
import { NodeId, Section } from '@flex-erp/types';
import { CmsButtonComponent } from '../primitives/button/cms-button.component';
import { CmsScrollAreaComponent } from '../primitives/scroll-area/cms-scroll-area.component';
import { CmsDialogComponent } from '../primitives/dialog/cms-dialog.component';

import {
  LucideAngularModule, GripVertical, ChevronRight, LayoutTemplate, LucideIconData, Columns2, Grid3x3, Mail, PanelBottom, Megaphone, CreditCard, Quote, FolderKanban, ImageIcon

} from 'lucide-angular';

@Component({
  selector: 'cms-sections-tree',
  standalone: true,
  imports: [CmsButtonComponent, CmsScrollAreaComponent, CmsDialogComponent, LucideAngularModule],
  templateUrl: './sections-tree.component.html',
  changeDetection: ChangeDetectionStrategy.OnPush,
  styles: [
    `
        :host {
          @apply h-full;
        }
      `,
  ],
})
export class CmsSectionsTreeComponent {
  @Input() sections: Section[] = [];
  @Input() selectedNodeId: NodeId | null = null;
  @Input() selectedNodeKind: 'section' | 'block' | null = null;

  @Output() openSectionLibrary = new EventEmitter<void>();
  @Output() selectNode = new EventEmitter<NodeId>();
  @Output() toggleVisibility = new EventEmitter<NodeId>();
  @Output() duplicateNode = new EventEmitter<NodeId>();
  @Output() removeNode = new EventEmitter<NodeId>();
  @Output() reorderSections = new EventEmitter<{ startIndex: number; endIndex: number }>();

  dragOverIndex: number | null = null;
  draggedIndex: number | null = null;
  expandedSections = new Set<string>();
  pendingDelete: Section | null = null;

  GripVertical = GripVertical;
  ChevronRight = ChevronRight;
  LayoutTemplate = LayoutTemplate;




  iconClass(icon: string): LucideIconData {
    const map: Record<string, LucideIconData> = {
      'layout-template': LayoutTemplate,
      image: ImageIcon,
      columns: Columns2,
      'grid-3x3': Grid3x3,
      mail: Mail,
      'panel-bottom': PanelBottom,
      megaphone: Megaphone,
      'credit-card': CreditCard,
      quote: Quote,
      'folder-kanban': FolderKanban,
    };
    return map[icon] || LayoutTemplate;
  }

  isSectionSelected(section: Section): boolean {
    return this.selectedNodeKind === 'section' && this.selectedNodeId === section.id;
  }

  isBlockSelected(sectionId: string, blockId: string): boolean {
    return this.selectedNodeKind === 'block' && this.selectedNodeId === blockId;
  }

  toggleExpanded(sectionId: string): void {
    if (this.expandedSections.has(sectionId)) {
      this.expandedSections.delete(sectionId);
      return;
    }
    this.expandedSections.add(sectionId);
  }

  onDragStart(event: DragEvent, index: number): void {
    this.draggedIndex = index;
    event.dataTransfer?.setData('text/plain', index.toString());
    event.dataTransfer?.setDragImage(new Image(), 0, 0);
  }

  onDragOver(event: DragEvent): void {
    event.preventDefault();
    if (event.dataTransfer) {
      event.dataTransfer.dropEffect = 'move';
    }
  }

  onDragEnter(index: number): void {
    if (this.draggedIndex !== null && this.draggedIndex !== index) {
      this.dragOverIndex = index;
    }
  }

  onDrop(event: DragEvent, targetIndex: number): void {
    event.preventDefault();
    const sourceIndex = Number(event.dataTransfer?.getData('text/plain'));
    if (!Number.isNaN(sourceIndex) && sourceIndex !== targetIndex) {
      this.reorderSections.emit({ startIndex: sourceIndex, endIndex: targetIndex });
    }
    this.dragOverIndex = null;
    this.draggedIndex = null;
  }

  onDragEnd(): void {
    this.dragOverIndex = null;
    this.draggedIndex = null;
  }

  confirmDelete(section: Section): void {
    this.pendingDelete = section;
  }

  cancelDelete(): void {
    this.pendingDelete = null;
  }

  deleteSection(): void {
    if (this.pendingDelete) {
      this.removeNode.emit(this.pendingDelete.id);
    }
    this.pendingDelete = null;
  }
}

<div
  class="w-[280px] bg-ui-bg-base border-r border-ui-border-base flex flex-col h-full"
>
  <div class="px-4 py-3 border-b border-ui-border-base">
    <h2 class="text-sm font-semibold text-ui-fg-base">Sections</h2>
    <p class="text-xs text-ui-fg-muted mt-0.5">Drag to reorder</p>
  </div>

  <cms-scroll-area className="flex-1">
    <div class="py-2" (dragend)="onDragEnd()">
      @if (sections.length === 0) {
      <div class="px-4 py-8 text-center">
        <p class="text-sm text-ui-fg-muted">No sections yet</p>
        <p class="text-xs text-ui-fg-muted mt-1">
          Click below to add your first section
        </p>
      </div>
      } @else { @for (section of sections; track section.id; let index = $index)
      {
      <div (dragenter)="onDragEnter(index)">
        <div
          class="relative"
          (dragover)="onDragOver($event)"
          (drop)="onDrop($event, index)"
        >
          @if (dragOverIndex === index) {
          <div
            class="absolute inset-x-0 top-0 h-0.5 bg-ui-bg-interactive z-10"
          ></div>
          }
          <div
            class="group flex items-center gap-2 px-3 py-2.5 cursor-pointer transition-colors border-l-2"
            [class.bg-ui-bg-subtle]="isSectionSelected(section)"
            [class.border-l-ui-border-interactive]="isSectionSelected(section)"
            [class.border-l-transparent]="!isSectionSelected(section)"
            [class.hover:bg-ui-bg-subtle-hover]="!isSectionSelected(section)"
            [class.opacity-50]="!section.visible"
            (click)="selectNode.emit(section.id)"
            (keydown.enter)="selectNode.emit(section.id)"
            (keydown.space)="
              $event.preventDefault(); selectNode.emit(section.id)
            "
            role="button"
            tabindex="0"
            draggable="true"
            (dragstart)="onDragStart($event, index)"
          >
            <div class="flex gp-1 items-center">
              <i-lucide
                class="p-0.5 -ml-1 cursor-grab active:cursor-grabbing opacity-0 group-hover:opacity-100 transition-opacity text-ui-fg-muted hover:text-ui-fg-base"
                [img]="GripVertical"
                (mousedown)="$event.stopPropagation()"
              ></i-lucide>

              @if (section.blocks.length > 0) {
              <i-lucide
                (click)="$event.stopPropagation(); toggleExpanded(section.id)"
                class="p-0.5 text-ui-fg-muted hover:text-ui-fg-base transition-colors -ml-0.5"
                [class.rotate-90]="expandedSections.has(section.id)"
                [img]="ChevronRight"
                (mousedown)="$event.stopPropagation()"
              ></i-lucide>
              } @else {
              <div class="w-6"></div>
              }
            </div>

            <i-lucide
              [img]="iconClass(section.icon)"
              class="w-4 h-4 text-muted-foreground shrink-0 text-ui-fg-muted hover:text-ui-fg-base'"
            ></i-lucide>

            <span class="text-sm font-medium truncate flex-1">{{
              section.name
            }}</span>

            <div
              class="flex items-center gap-0.5 opacity-0 group-hover:opacity-100 transition-opacity"
            >
              <button
                type="button"
                (click)="
                  $event.stopPropagation(); toggleVisibility.emit(section.id)
                "
                class="p-1.5 rounded hover:bg-ui-bg-subtle-hover text-ui-fg-muted hover:text-ui-fg-base transition-colors"
              >
                <i
                  class="pi"
                  [class.pi-eye]="section.visible"
                  [class.pi-eye-slash]="!section.visible"
                ></i>
              </button>
              <button
                type="button"
                (click)="
                  $event.stopPropagation(); duplicateNode.emit(section.id)
                "
                class="p-1.5 rounded hover:bg-ui-bg-subtle-hover text-ui-fg-muted hover:text-ui-fg-base transition-colors"
              >
                <i class="pi pi-copy text-xs"></i>
              </button>
              <button
                type="button"
                (click)="$event.stopPropagation(); confirmDelete(section)"
                class="p-1.5 rounded hover:bg-ui-button-danger/10 text-ui-fg-muted hover:text-ui-fg-error transition-colors"
              >
                <i class="pi pi-trash text-xs"></i>
              </button>
            </div>
          </div>

          @if (section.blocks.length > 0 && expandedSections.has(section.id)) {
          <div class="ml-9 border-l border-ui-border-base">
            @for (block of section.blocks; track block.id) {
            <div
              class="flex items-center gap-2 px-3 py-2 cursor-pointer transition-colors border-l-2"
              [class.bg-ui-bg-subtle]="isBlockSelected(section.id, block.id)"
              [class.border-l-ui-border-interactive]="
                isBlockSelected(section.id, block.id)
              "
              [class.border-l-transparent]="
                !isBlockSelected(section.id, block.id)
              "
              [class.hover:bg-ui-bg-subtle-hover]="
                !isBlockSelected(section.id, block.id)
              "
              (click)="selectNode.emit(block.id)"
              (keydown.enter)="selectNode.emit(block.id)"
              (keydown.space)="
                $event.preventDefault(); selectNode.emit(block.id)
              "
              role="button"
              tabindex="0"
            >
              <div class="w-1.5 h-1.5 rounded-full bg-ui-fg-muted"></div>
              <span class="text-sm text-ui-fg-muted">{{ block.name }}</span>
            </div>
            }
          </div>
          }
        </div>
      </div>
      } }
    </div>
  </cms-scroll-area>

  <div class="p-4 border-t border-ui-border-base">
    <cms-button
      variant="outline"
      className="w-full gap-2"
      (click)="openSectionLibrary.emit()"
    >
      <i class="pi pi-plus text-xs"></i>
      Add Section
    </cms-button>
  </div>
</div>

<cms-dialog
  [open]="!!pendingDelete"
  (openChange)="cancelDelete()"
  contentClass="w-full max-w-md rounded-lg border border-ui-border-base bg-ui-bg-base shadow-lg"
>
  <div class="p-6 space-y-4">
    <div>
      <h3 class="text-lg font-semibold text-ui-fg-base">Delete Section</h3>
      <p class="text-sm text-ui-fg-muted mt-2">
        Are you sure you want to delete "{{ pendingDelete?.name }}"? This action
        cannot be undone.
      </p>
    </div>
    <div class="flex justify-end gap-2">
      <cms-button variant="outline" (click)="cancelDelete()">Cancel</cms-button>
      <cms-button variant="destructive" (click)="deleteSection()"
        >Delete</cms-button
      >
    </div>
  </div>
</cms-dialog>
